### ISSUE TITLE
Rename DataSets folder as Datasets

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Datasets#10]
To be closed out in conjunction with https://github.com/BHoM/BHoM_UI/issues/132

**Comment by IsakNaslundBh** [comment]
Closing as resolved with the move to ProgramData
![image](https://user-images.githubusercontent.com/22005920/85381024-dd615f00-b53d-11ea-829f-e2d29aab3e5b.png)

@al-fisher , please reopen if you disagree
